name: Upload Image to Azure Blob

on:
  push:
    branches: 
      - dev
      - test

env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

jobs:
  upload-dev-assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Upload assets_dev to 'dev' container
      run: |
        echo "Uploading assets_dev to 'dev' container..."
        find assets_dev -type f | while read file; do
          blob_name=$(basename "$file")
          echo "Uploading $file as $blob_name..."
          az storage blob upload \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key "$AZURE_STORAGE_KEY" \
            --container-name dev \
            --name "$blob_name" \
            --file "$file" \
            --overwrite
        done

    # ---------- Test branch upload ----------
  upload-test-assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Upload assets_test to 'test' container
      run: |
        echo "Uploading assets_test to 'test' container..."
        find assets_test -type f | while read file; do
          blob_name=$(basename "$file")
          echo "Uploading $file as $blob_name..."
          az storage blob upload \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key "$AZURE_STORAGE_KEY" \
            --container-name test \
            --name "$blob_name" \
            --file "$file" \
            --overwrite
        done
