name: Upload Image to Azure Blob

on:
  push:
    branches: 
      - dev
    # paths:
    #   - 'assets/image.png'

jobs:
  upload-to-azure-blob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      uses: azure/setup-azure@v3

    - name: Upload image to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        az storage blob upload \
          --account-name $AZURE_STORAGE_ACCOUNT \
          --account-key "$AZURE_STORAGE_KEY" \
          --container-name image \
          --name image.png \
          --file assets/image1.png \
          --overwrite

