name: approval request for deployment

on:
  push:
    branches: [main]

jobs:
  create-approval-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create approval issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Deploy Approval Needed for Commit ${{ github.sha }}"
          content-filepath: .github/approval.md
          labels: approval, pending
          assignees: 045-ayush

